### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by nikolay** [trustpilot/beat-exporter#10]
[prometheus/client_golang](https://github.com/prometheus/client_golang) to [v0.9.2](https://github.com/prometheus/client_golang/releases/tag/v0.9.2)
[sirupsen/logrus](https://github.com/sirupsen/logrus) to [v1.2.0](https://github.com/sirupsen/logrus/releases/tag/v1.2.0)

**Comment by shivas** [comment]
Thanks, will do

**Comment by nikolay** [comment]
Thank you, @shivas! But I knew it - [logrus](https://github.com/sirupsen/logrus) recently got a new [v1.3.0](https://github.com/sirupsen/logrus/releases/tag/v1.3.0) release, and, of course, only a day after I opened this issue! 😄
