### ISSUE TITLE
beat_exporter error

### ISSUE THREAD

**Issue by andrewm659** [trustpilot/beat-exporter#14]
I am trying to setup beat_exporter as a systemd service.  However I am seeing the following errors when I start it.  I created its own user and told the group to be root.  I am running CentOS 7 latest.

`Apr 19 14:38:58 server1 filebeat_exporter[21087]: {"level":"error","message":"Could not load beat type, with error: Get 10.150.10.10: unsupported protocol scheme \"\", retrying in 5s","time":"2019-04-19T14:38:58-05:00"}`
`Apr 19 14:39:03 server1 filebeat_exporter[21087]: {"level":"error","message":"Could not load beat type, with error: Get 10.150.10.10: unsupported protocol scheme \"\", retrying in 5s","time":"2019-04-19T14:39:03-05:00"}`
`Apr 19 14:39:08 server1 filebeat_exporter[21087]: {"level":"error","message":"Could not load beat type, with error: Get 10.150.10.10: unsupported protocol scheme \"\", retrying in 5s","time":"2019-04-19T14:39:08-05:00"}`
`Apr 19 14:39:13 server1 filebeat_exporter[21087]: {"level":"error","message":"Could not load beat type, with error: Get 10.150.10.10: unsupported protocol scheme \"\", retrying in 5s","time":"2019-04-19T14:39:13-05:00"}`

Should I run this as root same as filebeat?

**Comment by shivas** [comment]
IMHO u need to configure filebeat_exporter with URLike endpoint, that is - provide `http://` in front of your IP/hostname of filebeat

**Comment by shivas** [comment]
in your case: `http://10.150.10.10`
