### ISSUE TITLE
Inconsistant naming of version

### ISSUE THREAD

**Issue by michael-doubez** [trustpilot/beat-exporter#27]
Hello,

Previous version was tagged v0.1.2 but latest bersion is tagged 0.2.0 (without leading 'v').

Is it a mistake or did you change your naming convention (it puts off my updating tool).

(Also, in the packages, a "." was transformed into a "-" but it make more sense like that)

Thanks for the exporter

**Comment by shivas** [comment]
Thanks for insights, yes, at version 0.2.0 some things changes (as whole CI/CD moved to Github actions), sorry for some inconveniences, but everything should stay as it is at version 0.2.0 for a while (no changes planned)
