### ISSUE TITLE
Publish release checksums

### ISSUE THREAD

**Issue by SuperQ** [trustpilot/beat-exporter#29]
It would be nice to publish `sha256sums.txt` for the release binaries for validation.

See [this example in Prometheus](https://github.com/prometheus/prometheus/releases/tag/v2.14.0).

**Comment by shivas** [comment]
Thanks, for suggestion, I take a look into it before doing next release.

**Comment by shivas** [comment]
@SuperQ there you go, checksum file attached: https://github.com/trustpilot/beat-exporter/releases/tag/0.3.0

**Comment by SuperQ** [comment]
Thanks!
