### ISSUE TITLE
Connection refused while using beat-exporter and port forward.

### ISSUE THREAD

**Issue by Daryjusz** [trustpilot/beat-exporter#51]
Hello
 I have created port forward from pod on cluster to locahost, which exposes filebeat metrics. 
Under http://localhost:5066/stats?pretty I can see those metrics without any problems(curl or browser).
When I run beat-exporter i have error message connection refused:
`{"level":"info","message":"Exploring target for beat type","time":"2021-11-30T09:57:45Z"}
{"level":"error","message":"Could not load beat type, with error: Get http://localhost:5066: dial tcp 127.0.0.1:5066: connect: connection refused, retrying in 1s","time":"2021-11-30T09:57:46Z"}
{"level":"error","message":"Could not load beat type, with error: Get http://localhost:5066: dial tcp 127.0.0.1:5066: connect: connection refused, retrying in 1s","time":"2021-11-30T09:57:47Z"}
{"level":"error","message":"Could not load beat type, with error: Get http://localhost:5066: dial tcp 127.0.0.1:5066: connect: connection refused, retrying in 1s","time":"2021-11-30T09:57:48Z"}
^C{"level":"info","message":"Signal received: interrupt","time":"2021-11-30T09:57:48Z"}
`
Does anyone had similar problem? If yes, what's the solution?
Thanks in advance.

**Comment by Daryjusz** [comment]
Deploying image on cluster inside pod with filebeat resolved my problem.

**Comment by jitender-negi** [comment]
@Daryjusz , I have filebeat deployed as  daemonset in EKS , I want to monitor it I know that i have to mention the things in the filebeat.yml that i can do , but I am unware of how to deploy this beats exporter in the cluster and then what to mention in the prometheus scrape file.
